spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mundobancario?serverTimezone=UTC
    username: root
    password: 1234 
  h2:
    console:
      enabled: true
      path: /console
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:      ddl-auto: update